helloworldapp/urls.py
from django.conf.urls import patterns, url
from django.conf import settings
from django.conf.urls import static
from helloworldapp import views


urlpatterns = [
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    # ex: /polls/5/
    url(r'^(?P<poll_id>\d+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<poll_id>\d+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<poll_id>\d+)/votes/$', views.votes, name='votes'),
    url(r'^contact/$', views.contact, name='contact'),

]

helloworldproject/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()
urlpatterns = [
    url(r'^helloworldapp/', include('helloworldapp.urls',namespace='polls')),
    url(r'^admin/', include(admin.site.urls)),
]
if settings.DEBUG:
     urlpatterns+=static(settings.STATIC_URL,doccument_root=settings.STATIC_ROOT)

helloworldapp/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __unicode__(self):
        return self.question

class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __unicode__(self):
        return self.choice_text

helloworldapp/forms.py
from django import forms
class ContactForm(forms.Form):
    subject=forms.CharField(max_length=100)
    message=forms.CharField()
    sender=forms.EmailField()
    cc_myself=forms.BooleanField(required=False)

helloworldapp/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse,HttpResponseRedirect
from helloworldapp.models import Poll
from django.template import Context, loader
from .forms import ContactForm
from django.http import Http404
def index(request):
    latest_poll_list = Poll.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    # template = loader.get_template('base.html')
    context = Context({
        'latest_poll_list': latest_poll_list,
    })
    return HttpResponse(template.render(context))

def detail(request, poll_id):
    try:
        poll = Poll.objects.get(pk=poll_id)
    except Poll.DoesNotExist:
       # raise Http404
        return render(request, '404.html')
    return render(request, 'detail.html', {'poll': poll})

def results(request, poll_id):
    return HttpResponse("You're looking at the results of poll %s." % poll_id)

def votes(request, poll_id):
    return HttpResponse("You're voting on poll %s." % poll_id)
def contact(request):
    form =ContactForm(request.POST or None)
    if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            sender = form.cleaned_data['sender']
            cc_myself = form.cleaned_data['cc_myself']
            recipient = ['studentmanik@gmail.com']
            if cc_myself:
                recipient.append(sender)
            from django.core.mail import send_mail

            send_mail(subject, message, sender, recipient)
            return HttpResponseRedirect('/helloworldapp/contact') # Redirect after post
    else:

        # Dynamic initial values.
        form = ContactForm(initial={'sender': 'studentmanik@gmail.com'})
    context={
        'title':'Contact us',
        'form':form,
    }
    return render(request,'polls/contact.html',context)

helloworldapp/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}Latest Poll List{% endblock %}</title>
    {% block stylesheets %}
        {% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-responsive.min.css' %}"/>
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>
        <script type="text/javascript" src="{% static 'js/jquery-2.0.2.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    {% endblock %}
</head>

<body>
<div class="container-narrow">
    <div class="masthead">

        <ul class="nav nav-pills pull-right">
            <li class="active"><a href="{% url 'polls:index' %}">Home</a></li>
            <li><a href="{% url 'polls:index' %}">About</a></li>
            <li><a href="{% url 'polls:contact' %}">Contact</a></li>
        </ul>
        <h3 class="muted">{% block header_title %}Poll App{% endblock %}</h3>
    </div>
    <hr>
    {% block body %}

    {% endblock %}
    <div class="footer">
        <p>&copy; Shibly 2013</p>
    </div>
</div>
</body>
</html>

helloworldapp/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ poll.question}}
{{poll.id}}
</body>
</html>

helloworldapp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if latest_poll_list %}
    <ul>
    {% for poll in latest_poll_list %}
        <li><a href="/helloworldapp/{{ poll.id }}/detail/">{{ poll.question }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
</body>
</html>

helloworldapp/templates/polls/about.html
{% extends "polls/index.html" %}
{% block title %}About Poll App{% endblock %}
{% block body %}
    <div class="alert alert-info about">
        <h3 id="about">About poll app</h3>
    </div>
    <p>
        Online poll app is a django powered polling application influenced by Abu Ashraf Masnun's recent tutorial
        and official tutorial from Django's site. The app does a fairly simple job :). User will select a poll , choose
        an answer and vote it. An immediate result will be displayed just after the vote. The app uses django's builtin
        admin
        app and hook the poll app in it to provide an interface to perform CRUID operation on the app.

    </p>
{% endblock %}

helloworldapp/templates/polls/contact.html
{% extends "base.html" %}
{% block title %}About Poll App{% endblock %}
{% block body %}
    <div class="alert alert-info about">
        <h3 id="about">Contact Us</h3>
    </div>
    <form action="/helloworldapp/contact/" method="post" class="form-vote"
          {% if form.is_multipart %}enctype="multipart/form-data"{% endif %}>{% csrf_token %}
        {{ form.non_field_errors }}
        <div class="fieldWrapper">
            {% if form.subject.errors %}
                <div class="alert alert-error">
                    {{ form.subject.errors }}
                </div>
            {% endif %}
            <label for="id_subject">Email subject:</label>
            {{ form.subject }}
        </div>
        <div class="fieldWrapper">
            {% if form.message.errors %}
                <div class="alert alert-error">
                    {{ form.message.errors }}
                </div>
            {% endif %}
            <label for="id_message">Your message:</label>
            {{ form.message }}
        </div>
        <div class="fieldWrapper">
            {% if form.sender.errors %}
                <div class="alert alert-error">
                    {{ form.sender.errors }}
                </div>
            {% endif %}
            <label for="id_sender">Your email address:</label>
            {{ form.sender }}
        </div>
        <div class="fieldWrapper">
            {% if form.cc_myself.errors %}
                <div class="alert alert-error">
                    {{ form.cc_myself.errors }}
                </div>
            {% endif %}
            <label for="id_cc_myself">CC yourself?</label>
            {{ form.cc_myself }}
        </div>
        <input type="submit" class="btn btn-primary" value="Contact Us"/>
    </form>
{% endblock %}

helloworldapp/templates/polls/detail.html
{% extends "polls/index.html" %}
{% block title %}Poll Detail {% endblock %}
{% block body %}
    <div class="alert alert-success">
        <h2>{{ poll.question }}</h2>
    </div>
    {% if error_message %}
        <div class="alert alert-error">
            <p><strong>{{ error_message }}</strong></p>
        </div>
    {% endif %}
    <form class="form-vote" action="{% url 'polls:vote' poll.id %}" method="post">
        {% csrf_token %}
        {% for choice in poll.choice_set.all %}
            <input type="radio" class="radio inline control-label" name="choice" id="choice{{ forloop.counter }}"
                   value="{{ choice.id }}"/>
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br/>
        {% endfor %}
        <input type="submit" value="Vote" class="btn btn-primary"/>
    </form>

{% endblock %}

helloworldapp/templates/polls/details.html
<!DOCTYPE html>
<html>
<head>
    <title>Poll No Found</title>
</head>
<body>
{{ poll }}

</body>
</html>

helloworldapp/templates/polls/index.html
{% extends 'base.html' %}

    {% block body %}
        <table class="table table-striped table-bordered">
            <thead>
            <tr class="success">
                <th>Click on a poll bellow</th>
            </tr>
            </thead>
            <tbody>
            {% if latest_poll_list %}
                {% for poll in latest_poll_list %}
                    <tr>
                    <td>
                        <a href="{% url 'polls:detail' poll.id %}">{{ poll.question }}</a>
                    </td>
                {% endfor %}
            {% else %}
                <td>Currently No polls are available.</td>
            {% endif %}
            </tr>
            </tbody>
        </table>
    {% endblock %}

helloworldapp/templates/polls/results.html
{% extends "polls/index.html" %}
{% block title %}Poll Result {% endblock %}

{% block body %}
    <div class="alert alert-success">
        <h2>{{ poll.question }}</h2>
    </div>
    <h3>Here is the result</h3>

    <ul>
        {% for choice in poll.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
    </ul>
    <ul>
        <li><a href="{% url 'polls:detail' poll.id %}">Vote again?</a></li>
        <li><a href="{% url 'polls:index' %}">Go back to Poll index</a></li>
    </ul>
{% endblock %}